### ISSUE TITLE
Diseño de la web

### ISSUE THREAD

**Issue by lizfp0** [julenecheberria/apinetcurso#4]
La web no es responsive por lo que observo. Sí esta en pantalla de ordenador se visualiza correctamente todas sus funciones.

![Image](https://github.com/user-attachments/assets/74142b35-aee7-46f5-9bd2-745863bc1826)

Pero si la web se visualiza en una pantalla más pequeña como por ejemplo en una Tablet o en un móvil, estos datos se verán distorsionados.

![Image](https://github.com/user-attachments/assets/0f5674a6-f628-47a8-a49a-90bb1b76b0c6)

**Comment by julenecheberria** [comment]
Eluso que se le da a eata aplicación obliga a mantener una gran catidad de datos en la pantalla y a ser utilizada con un mínimo de resolución horizontal. 
Aunque el framework usado si es responsible, no puede con tal cantdad  dedatos.
La cantidad d edatos que se muestra forma parte de las especificaciones del cliente y asume estas limintaciones
