### ISSUE TITLE
Orden del menú del expediente a seleccionar

### ISSUE THREAD

**Issue by lizfp0** [julenecheberria/apinetcurso#5]
Al darle clic a los 3 puntitos al lado izquierdo del expediente, se despliega este menú:

![Image](https://github.com/user-attachments/assets/2227c074-f58c-43fb-8fc6-481027606995)

Se vería mejor cambiar el orden del menú porque cuando uno hace clic en los 3 puntitos de un expediente, primero se debería de ver la opción de visualizar el expediente o el de editar que es lo que normalmente vemos en algunas aplicaciones web. 
Pienso que así sería mejor para los usuarios.

**Comment by julenecheberria** [comment]
El orden ha sido elegido por el cliente.
En realidad, las operaciones de edición son raras, un expediente, lote o línea sufre muy pocas modificaicones por parte del usuario
